GET https://phonebook-fso-logi.onrender.com/api/persons

###
GET https://phonebook-fso-logi.onrender.com/api/persons/info

###
DELETE https://phonebook-fso-logi.onrender.com/api/persons/1

###
POST http://localhost:3001/api/persons
CONTENT-Type: application/json

{
"name": "Niklas",
"number": "92948433"}