GET https://phonebook-fso-logi.onrender.com/api/persons

###
GET https://phonebook-fso-logi.onrender.com/api/persons/info

###
DELETE https://phonebook-fso-logi.onrender.com/api/persons/1

###
POST https://phonebook-fso-logi.onrender.com/api/persons/
CONTENT-Type: application/json

{
"name": "Flausch",
"number": "0290966"}