GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons/
CONTENT-Type: application/json

{
"name": "Carina",
"number": "0290966"}